name: modflow6

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - appdirs
  - filelock
  - fprettify
  - fortran-language-server
  - jupytext
  - matplotlib
  - meson=1.3.0
  - ninja
  - numpy
  - pyshp
  - shapely
  - pip
  - pip:
      - git+https://github.com/spaulins-usgs/flopy.git@develop
      - git+https://github.com/modflowpy/pymake.git
      - git+https://github.com/Deltares/xmipy.git
      - git+https://github.com/MODFLOW-USGS/modflowapi.git
      - git+https://github.com/MODFLOW-USGS/modflow-devtools.git
  - pytest
  - pytest-dotenv
  - pytest-order
  - pytest-xdist
  - flaky
  - netcdf4
