name: Test NetCDF MF6 (Windows)
description: Build and test NetCDF MODFLOW 6 on Windows
runs:
  using: "composite"
  steps:

    - name: Build MF6 NetCDF
      uses: ./modflow6/.github/actions/build-netcdf-win

    - name: Build MF6 NetCDF
      uses: ./modflow6/.github/actions/build-netcdf-mf6

    - name: Update flopy
      working-directory: modflow6
      shell: cmd
      run: pixi run update-flopy

    - name: Get executables
      working-directory: modflow6/autotest
      shell: cmd
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: pixi run get-exes

    - name: Convert unix2dos
      shell: cmd
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\test_modflow6_netcdf.bat" "%TEMP%\test_modflow6_netcdf.bat"

    - name: Test programs
      if: github.ref_name != 'master'
      shell: cmd
      env:
        REPOS_PATH: ${{ github.workspace }}
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\test_modflow6_netcdf.bat"

    - name: Test programs
      if: github.ref_name == 'master'
      shell: cmd
      env:
        REPOS_PATH: ${{ github.workspace }}
        MARKERS: not developmode
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\test_modflow6_netcdf.bat"
