#!/bin/bash

gfortran -o test -fimplicit-none  -Wall  -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace -I/opt/local/include -L/opt/local/lib ./test.f90 -lnetcdff -lnetcdf
