#!/bin/bash

gfortran -o test -Og -fimplicit-none  -Wall  -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace -I/Users/runner/environments/1.14.3-v4.9.0/include -I/Users/runner/environments/netcdf-fortran-4.6.1/include -L/Users/runner/environments/1.14.3-v4.9.0/lib -L/Users/runner/environments/netcdf-fortran-4.6.1/lib ./test.f90 -lnetcdff -lnetcdf
