#!/bin/bash

gfortran -o test -Og -fimplicit-none  -Wall  -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace -I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ ./test.f90 -lnetcdff -lnetcdf
