#!/bin/bash

gfortran -o test -O2 -fimplicit-none  -Wall  -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace -I/usr/local/Cellar/netcdf/4.9.2_1/include -I/usr/local/Cellar/netcdf-fortran/4.6.1/include -L/usr/local/Cellar/netcdf/4.9.2_1/lib -L/usr/local/Cellar/netcdf-fortran/4.6.1/lib ./test.f90 -lnetcdff -lnetcdf
