#!/bin/bash

gfortran -o test -I/usr/local/Cellar/netcdf/4.9.2_1/include -I/usr/local/Cellar/netcdf-fortran/4.6.1/include -L/usr/local/Cellar/netcdf/4.9.2_1/lib -L/usr/local/Cellar/netcdf-fortran/4.6.1/include/lib ./test.f90 -lnetcdff -lnetcdf 
