name: Build NetCDF (Windows)
description: Build NetCDF on Windows
runs:
  using: "composite"
  steps:
    - name: Convert line endings
      shell: cmd
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\compile_netcdf.bat" "%TEMP%\compile_netcdf.bat"

    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Set netcdf-c prefix from pixi environment
      shell: bash
      run: |
        echo "NETCDF_C_PREFIX=$GITHUB_WORKSPACE/modflow6/.pixi/envs/default/Library" >> $GITHUB_ENV

    - name: Download NetCDF-Fortran
      shell: bash
      run: |
        mkdir -p netcdf/netcdf-fortran-4.6.2/build
        cd netcdf/netcdf-fortran-4.6.2
        curl https://downloads.unidata.ucar.edu/netcdf-fortran/4.6.2/netcdf-fortran-4.6.2.zip -O -J
        unzip netcdf-fortran-4.6.2.zip
        # disable system hdf5 library check
        sed -i '485s/^/#/' netcdf-fortran-4.6.2/CMakeLists.txt

    - name: Setup oneAPI
      uses: ./modflow6/.github/actions/setup-par-oneapi

    - name: Build NetCDF
      shell: cmd
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\compile_netcdf.bat"

    - name: Update path for NetCDF libs
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/netcdf/netcdf-fortran-4.6.2/build/fortran" >> $GITHUB_PATH
